// app/layout.js
// import './globals.css'

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function AuthLayout({ 
  children,
 }: {
  children: React.ReactNode
 }) {
  return (
    <html lang="en">
      <body>
        
        {children}

        <footer style={{
          backgroundColor:"pink",
          padding:"1rem"
        }}>Footer</footer>
      </body>
      
    </html>
  )
}
